[context.production.environment]
  REACT_APP_LAUNCHPAD_API_URL="https://wt-launchpad.it.auth0.com/api/run/launchpad/launchpad"
  REACT_APP_AUTH0_DOMAIN="meteor.auth0.com"
  REACT_APP_AUTH0_CLIENT_ID="V84GiB4Ltbh6_5m7k-4lA2kD7mrD-mBh"

[context.deploy-preview.environment]
  REACT_APP_LAUNCHPAD_API_URL = "https://wt-launchpad.it.auth0.com/api/run/launchpad-staging/launchpad"
  REACT_APP_AUTH0_DOMAIN = "meteor.auth0.com"
  REACT_APP_AUTH0_CLIENT_ID = "kUtxJjyapGN72Rs7tt5jXMgQ7axDgJLa"
